"""init

Revision ID: 936891f269e6
Revises: 
Create Date: 2026-10-05 18:48:02.480250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936891f269e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('device_no', sa.String(length=64), nullable=False, comment='设备编号（唯一）'),
    sa.Column('model', sa.String(length=64), nullable=False, comment='设备型号'),
    sa.Column('status', sa.Enum('online', 'offline', 'fault', 'maintenance', name='device_status', native_enum=False, length=20), server_default='offline', nullable=False, comment='状态：online/offline/fault/maintenance'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='安装位置/所属车辆'),
    sa.Column('last_online_at', sa.DateTime(), nullable=True, comment='最后在线时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_device_no'), ['device_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录用户名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt 加密后的密码'),
    sa.Column('role', sa.Enum('admin', 'engineer', 'viewer', name='user_role', native_enum=False, length=20), server_default='viewer', nullable=False, comment='角色：admin/engineer/viewer'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('device_id', sa.Integer(), nullable=False, comment='关联设备 ID'),
    sa.Column('type', sa.Enum('offline', 'fault', 'overspeed', 'low_battery', 'other', name='alert_type', native_enum=False, length=20), server_default='other', nullable=False, comment='告警类型：offline/fault/overspeed/low_battery/other'),
    sa.Column('content', sa.Text(), nullable=True, comment='告警内容'),
    sa.Column('is_false_positive', sa.Boolean(), server_default='0', nullable=False, comment='是否误报'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_is_false_positive'), ['is_false_positive'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_type'), ['type'], unique=False)

    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作人 ID（系统操作可为空）'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='动作，如 create/update/delete/login'),
    sa.Column('target', sa.String(length=100), nullable=True, comment='操作对象，如 ticket:12'),
    sa.Column('detail', sa.Text(), nullable=True, comment='操作详情'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_user_id'), ['user_id'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='工单标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='问题描述'),
    sa.Column('device_id', sa.Integer(), nullable=False, comment='关联设备 ID'),
    sa.Column('creator_id', sa.Integer(), nullable=False, comment='创建人 ID'),
    sa.Column('assignee_id', sa.Integer(), nullable=True, comment='负责人 ID'),
    sa.Column('status', sa.Enum('pending', 'processing', 'resolved', 'closed', name='ticket_status', native_enum=False, length=20), server_default='pending', nullable=False, comment='状态：pending/processing/resolved/closed'),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='ticket_priority', native_enum=False, length=20), server_default='medium', nullable=False, comment='优先级：low/medium/high/urgent'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_title'), ['title'], unique=False)

    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('ticket_id', sa.Integer(), nullable=False, comment='所属工单 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='评论人 ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_comments_ticket_id'), ['ticket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_comments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_comments_ticket_id'))

    op.drop_table('ticket_comments')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_title'))
        batch_op.drop_index(batch_op.f('ix_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_tickets_priority'))
        batch_op.drop_index(batch_op.f('ix_tickets_device_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_creator_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_assignee_id'))

    op.drop_table('tickets')
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_action'))

    op.drop_table('operation_logs')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_type'))
        batch_op.drop_index(batch_op.f('ix_alerts_is_false_positive'))
        batch_op.drop_index(batch_op.f('ix_alerts_device_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_status'))
        batch_op.drop_index(batch_op.f('ix_devices_device_no'))

    op.drop_table('devices')
    # ### end Alembic commands ###
