"""Pydantic v2 数据模式包（请求体 / 响应体）."""

from app.schemas.alert import (
    AlertCreate,
    AlertDetail,
    AlertFalsePositiveUpdate,
    AlertOut,
    AlertPage,
    AlertTopItem,
    AlertUpdate,
)
from app.schemas.device import (
    DeviceBrief,
    DeviceCreate,
    DeviceOut,
    DevicePage,
    DeviceUpdate,
)
from app.schemas.stats import (
    AlertStats,
    AlertTopStats,
    DashboardStats,
    DeviceStatusStats,
    OverviewStats,
    TicketByStatusStats,
    TicketPriorityStats,
    TicketStatusCount,
    TicketStatusStats,
    TrendPoint,
    TrendSeries,
)
from app.schemas.ticket import (
    TicketAssignRequest,
    TicketCommentCreate,
    TicketCommentOut,
    TicketCreate,
    TicketDetail,
    TicketOut,
    TicketPage,
    TicketStatusUpdate,
    TicketUpdate,
)
from app.schemas.user import (
    LoginRequest,
    OperationLogOut,
    Token,
    TokenPayload,
    UserCreate,
    UserInDB,
    UserOut,
    UserRoleUpdate,
    UserUpdate,
)

__all__ = [
    "AlertCreate",
    "AlertDetail",
    "AlertFalsePositiveUpdate",
    "AlertOut",
    "AlertPage",
    "AlertStats",
    "AlertTopItem",
    "AlertTopStats",
    "AlertUpdate",
    "DashboardStats",
    "DeviceBrief",
    "DeviceCreate",
    "DeviceOut",
    "DevicePage",
    "DeviceStatusStats",
    "DeviceUpdate",
    "LoginRequest",
    "OperationLogOut",
    "OverviewStats",
    "TicketCommentCreate",
    "TicketCommentOut",
    "TicketCreate",
    "TicketDetail",
    "TicketOut",
    "TicketPage",
    "TicketPriorityStats",
    "TicketAssignRequest",
    "TicketByStatusStats",
    "TicketStatusUpdate",
    "TicketStatusCount",
    "TicketStatusStats",
    "TicketUpdate",
    "Token",
    "TokenPayload",
    "TrendPoint",
    "TrendSeries",
    "UserCreate",
    "UserInDB",
    "UserOut",
    "UserRoleUpdate",
    "UserUpdate",
]
